### PR TITLE
Fix prompt menu for Zotero 7

### LINKED ISSUE #14: Zotero 7 support
HI!  Big fan of this add-on.  It looks like somehow the context-menu no longer shows "Fetch PMCID" in Zotero 7.  The add-on can be successfully installed though - wondering if there are any tweaks?  Thanks!

### PR DESCRIPTION
**Pull request by alexreg**
Resolves #14.

### CODE REVIEW

**Comment by retorquere** [comment]
Can you remove all stuff related to `worker`? It does not apply to the fetcher.

**Comment by alexreg** [comment]
@retorquere Ah yes, indeed. It looks like you've already done it yourself by now? Appreciate the merge, in any case!

**Comment by retorquere** [comment]
Sorry I didn't act sooner - I'm a bit swamped

**Comment by alexreg** [comment]
@retorquere No worries, I quite understand.

For the record, I've been using this fix in Zotero the past few weeks, and it seems to have done the job for me. But feel free to wait for more testing/feedback before a release, of course.

**Pull request merged**
